trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: graphql-test-secrets

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "CLIENT_ID=$(CLIENT_ID)" > .env
    echo "CLIENT_SECRET=$(CLIENT_SECRET)" >> .env
    echo "TENANT_ID=$(TENANT_ID)" >> .env
    echo "SCOPE=$(SCOPE)" >> .env
    echo "API_URL=$(API_URL)" >> .env
  displayName: 'Set up environment variables'

- script: |
    pytest --html=report.html --self-contained-html
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'report.html'
    artifact: 'TestReport'
    publishLocation: 'pipeline'
  condition: succeededOrFailed() 